<?php
/**
 * Plugin settings
 *
 * @package Teydea_Studio\Custom_Login
 */

namespace Teydea_Studio\Custom_Login;

use Teydea_Studio\Custom_Login\Dependencies\Utils;
use Teydea_Studio\Custom_Login\Dependencies\Validatable_Fields;
use Teydea_Studio\Custom_Login\Styles;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * The "Settings" class
 *
 * @phpstan-import-type Type_Settings_Fields_Config from Utils\Settings
 */
class Settings extends Utils\Settings {
	/**
	 * Common definitions
	 *
	 * @var array<string,array<string>>
	 */
	public array $common_defs = [
		'alignment_matrix'   => [
			'bottom center',
			'bottom left',
			'bottom right',
			'center center',
			'center left',
			'center right',
			'default',
			'top center',
			'top left',
			'top right',
		],
		'border_style'       => [
			'dashed',
			'dotted',
			'none',
			'solid',
		],
		'font_families'      => [],
		'font_weights'       => [
			'100',
			'100italic',
			'200',
			'200italic',
			'300',
			'300italic',
			'400',
			'400italic',
			'500',
			'500italic',
			'600',
			'600italic',
			'700',
			'700italic',
			'800',
			'800italic',
			'900',
			'900italic',
		],
		'letter_case'        => [
			'capitalize',
			'lowercase',
			'none',
			'uppercase',
		],
		'size_repeat'        => [
			'size-auto--no-repeat',
			'size-auto--repeat',
			'size-auto--repeat-round',
			'size-auto--repeat-space',
			'size-auto--repeat-x',
			'size-auto--repeat-y',
			'size-contain--no-repeat',
			'size-contain--repeat',
			'size-contain--repeat-x',
			'size-contain--repeat-y',
			'size-cover',
		],
		'social_media_icons' => [
			'fontawesome-discord',
			'fontawesome-dribbble',
			'fontawesome-facebook-f',
			'fontawesome-facebook-messenger',
			'fontawesome-figma',
			'fontawesome-flickr',
			'fontawesome-github',
			'fontawesome-instagram',
			'fontawesome-linkedin-in',
			'fontawesome-mastodon',
			'fontawesome-meetup',
			'fontawesome-pinterest-p',
			'fontawesome-reddit',
			'fontawesome-slack',
			'fontawesome-threads',
			'fontawesome-tiktok',
			'fontawesome-tumblr',
			'fontawesome-twitch',
			'fontawesome-twitter',
			'fontawesome-vimeo-v',
			'fontawesome-whatsapp',
			'fontawesome-wordpress',
			'fontawesome-x-twitter',
			'fontawesome-youtube',
		],
	];

	/**
	 * Construct the object
	 *
	 * @param Utils\Container                   $container Container instance.
	 * @param array<string,array<string,mixed>> $config    Configuration data; if not provided, data will be loaded from the database.
	 */
	public function __construct( Utils\Container $container, ?array $config = null ) {
		$this->container     = $container;
		$this->fields_config = $this->get_fields_config();

		/**
		 * Use the parent constructor
		 */
		parent::__construct( $this->container, $this->fields_config, $config );
	}

	/**
	 * Get the fields configuration
	 *
	 * @return Type_Settings_Fields_Config Fields configuration.
	 */
	protected function get_fields_config(): array {
		// Get the list of known fonts.
		$preconfigured_styles               = ( new Styles( $this->container ) )->get_preconfigured_styles();
		$this->common_defs['font_families'] = array_keys( $preconfigured_styles['font_families'] );

		// Get the list of installed languages.
		$languages = Utils\Languages::get_installed_languages( 'core' );

		// The fields configuration.
		$fields_config = [
			'custom_css'                      => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'css' => Validatable_Fields\Configuration::css_field(),
				],
			],
			'background'                      => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'color'         => Validatable_Fields\Configuration::string_field( '#f0f0f1' ),
					'focal_point_x' => Validatable_Fields\Configuration::float_field( 0.5, 0, 1, 2 ),
					'focal_point_y' => Validatable_Fields\Configuration::float_field( 0.5, 0, 1, 2 ),
					'media_id'      => Validatable_Fields\Configuration::media_id_field( 0, [ 'image' ] ),
					'size_repeat'   => Validatable_Fields\Configuration::string_of_choice_field( 'size-cover', $this->common_defs['size_repeat'] ),
				],
			],
			'logo'                            => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'       => Validatable_Fields\Configuration::string_of_choice_field( 'center', [ 'left', 'center', 'right' ] ),
					'as_link'         => Validatable_Fields\Configuration::boolean_field( true ),
					'link'            => Validatable_Fields\Configuration::url_field( 'https://wordpress.org/' ),
					'media_id'        => Validatable_Fields\Configuration::media_id_field( 0, [ 'image' ] ),
					'open_in_new_tab' => Validatable_Fields\Configuration::boolean_field( false ),
					'show'            => Validatable_Fields\Configuration::boolean_field( true ),
					'strict_width'    => Validatable_Fields\Configuration::integer_field( 0, 0, 1000 ),
					'logo_source'     => Validatable_Fields\Configuration::string_of_choice_field( 'core', [ 'core', 'custom', 'site_icon' ] ),
				],
			],
			'login_form_container'            => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'                    => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['alignment_matrix'] ),
					'background_color'             => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'border_bottom_color'          => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_bottom_color_on_focus' => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_bottom_color_on_hover' => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_bottom_left_radius'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_right_radius'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_style'          => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_focus' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_hover' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_width'          => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_focus' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_hover' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_color'            => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_left_color_on_focus'   => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_left_color_on_hover'   => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_left_style'            => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_focus'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_hover'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_width'            => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_focus'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_hover'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_color'           => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_right_color_on_focus'  => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_right_color_on_hover'  => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_right_style'           => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_focus'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_hover'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_width'           => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_focus'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_hover'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_color'             => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_top_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_top_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#c3c4c7' ),
					'border_top_left_radius'       => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_right_radius'      => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_style'             => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_focus'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_hover'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_width'             => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_focus'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_hover'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'focal_point_x'                => Validatable_Fields\Configuration::float_field( 0.5, 0, 1, 2 ),
					'focal_point_y'                => Validatable_Fields\Configuration::float_field( 0.5, 0, 1, 2 ),
					'margin_bottom'                => Validatable_Fields\Configuration::unit_field( '24px' ),
					'margin_left'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'                 => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'                   => Validatable_Fields\Configuration::unit_field( '24px' ),
					'media_id'                     => Validatable_Fields\Configuration::media_id_field( 0, [ 'image' ] ),
					'padding_bottom'               => Validatable_Fields\Configuration::unit_field( '26px' ),
					'padding_left'                 => Validatable_Fields\Configuration::unit_field( '24px' ),
					'padding_right'                => Validatable_Fields\Configuration::unit_field( '24px' ),
					'padding_top'                  => Validatable_Fields\Configuration::unit_field( '26px' ),
					'shadow'                       => Validatable_Fields\Configuration::string_field( '0 1px 3px rgba(0,0,0,.04)' ),
					'shadow_on_focus'              => Validatable_Fields\Configuration::string_field( '0 1px 3px rgba(0,0,0,.04)' ),
					'shadow_on_hover'              => Validatable_Fields\Configuration::string_field( '0 1px 3px rgba(0,0,0,.04)' ),
					'size_repeat'                  => Validatable_Fields\Configuration::string_of_choice_field( 'size-cover', $this->common_defs['size_repeat'] ),
					'width'                        => Validatable_Fields\Configuration::integer_field( 320, 0, 1000 ),
					'wrap_links_in_container'      => Validatable_Fields\Configuration::boolean_field( false ),
					'wrap_logo_in_container'       => Validatable_Fields\Configuration::boolean_field( false ),
					'wrapper_padding_bottom'       => Validatable_Fields\Configuration::unit_field( '0px' ),
					'wrapper_padding_left'         => Validatable_Fields\Configuration::unit_field( '0px' ),
					'wrapper_padding_right'        => Validatable_Fields\Configuration::unit_field( '0px' ),
					'wrapper_padding_top'          => Validatable_Fields\Configuration::unit_field( '0px' ),
				],
			],
			'login_form_labels'               => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'show'           => Validatable_Fields\Configuration::boolean_field( true ),
					'font_family'    => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'      => Validatable_Fields\Configuration::unit_field( '14px' ),
					'font_weight'    => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'letter_case'    => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['letter_case'] ),
					'line_height'    => Validatable_Fields\Configuration::float_field( 1.5, 0 ),
					'margin_bottom'  => Validatable_Fields\Configuration::unit_field( '3px' ),
					'margin_left'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'     => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_bottom' => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_right'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_top'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'text_color'     => Validatable_Fields\Configuration::string_field( '#3c434a' ),
				],
			],
			'login_form_input_fields'         => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'background_color'             => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'border_bottom_color'          => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_bottom_color_on_focus' => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_bottom_color_on_hover' => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_bottom_left_radius'    => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_bottom_right_radius'   => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_bottom_style'          => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_focus' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_hover' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_width'          => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_focus' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_hover' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_color'            => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_left_color_on_focus'   => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_left_color_on_hover'   => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_left_style'            => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_focus'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_hover'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_width'            => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_focus'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_hover'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_color'           => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_right_color_on_focus'  => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_right_color_on_hover'  => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_right_style'           => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_focus'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_hover'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_width'           => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_focus'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_hover'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_color'             => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_top_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_top_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_top_left_radius'       => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_top_right_radius'      => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_top_style'             => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_focus'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_hover'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_width'             => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_focus'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_hover'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'eye_icon_color'               => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'eye_icon_color_on_focus'      => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'eye_icon_color_on_hover'      => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'font_family'                  => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'                    => Validatable_Fields\Configuration::unit_field( '24px' ),
					'font_weight'                  => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'line_height'                  => Validatable_Fields\Configuration::float_field( 1.33, 0 ),
					'margin_bottom'                => Validatable_Fields\Configuration::unit_field( '16px' ),
					'margin_left'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'                 => Validatable_Fields\Configuration::unit_field( '6px' ),
					'margin_top'                   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_bottom'               => Validatable_Fields\Configuration::unit_field( '0.1875rem' ),
					'padding_left'                 => Validatable_Fields\Configuration::unit_field( '0.3125rem' ),
					'padding_right'                => Validatable_Fields\Configuration::unit_field( '0.3125rem' ),
					'padding_top'                  => Validatable_Fields\Configuration::unit_field( '0.1875rem' ),
					'placeholder_color'            => Validatable_Fields\Configuration::string_field(),
					'shadow'                       => Validatable_Fields\Configuration::string_field(),
					'shadow_on_focus'              => Validatable_Fields\Configuration::string_field( '0 0 0 1px #2271b1' ),
					'shadow_on_hover'              => Validatable_Fields\Configuration::string_field(),
					'text_color'                   => Validatable_Fields\Configuration::string_field( '#2c3338' ),
					'text_color_on_focus'          => Validatable_Fields\Configuration::string_field( '#2c3338' ),
					'text_color_on_hover'          => Validatable_Fields\Configuration::string_field( '#2c3338' ),
				],
			],
			'login_form_checkbox_fields'      => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'background_color'                  => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_checked'          => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_on_focus'         => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_on_focus_checked' => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_on_hover'         => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'background_color_on_hover_checked' => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'border_bottom_color'               => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_bottom_color_on_focus'      => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_bottom_color_on_hover'      => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_bottom_left_radius'         => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_bottom_right_radius'        => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_bottom_style'               => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_focus'      => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_hover'      => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_width'               => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_focus'      => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_hover'      => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_color'                 => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_left_color_on_focus'        => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_left_color_on_hover'        => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_left_style'                 => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_focus'        => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_hover'        => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_width'                 => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_focus'        => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_hover'        => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_color'                => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_right_color_on_focus'       => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_right_color_on_hover'       => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_right_style'                => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_focus'       => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_hover'       => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_width'                => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_focus'       => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_hover'       => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_color'                  => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_top_color_on_focus'         => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_top_color_on_hover'         => Validatable_Fields\Configuration::string_field( '#8c8f94' ),
					'border_top_left_radius'            => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_top_right_radius'           => Validatable_Fields\Configuration::unit_field( '4px' ),
					'border_top_style'                  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_focus'         => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_hover'         => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_width'                  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_focus'         => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_hover'         => Validatable_Fields\Configuration::unit_field( '1px' ),
					'field_margin_bottom'               => Validatable_Fields\Configuration::unit_field( '0rem' ),
					'field_margin_left'                 => Validatable_Fields\Configuration::unit_field( '0rem' ),
					'field_margin_right'                => Validatable_Fields\Configuration::unit_field( '0.25rem' ),
					'field_margin_top'                  => Validatable_Fields\Configuration::unit_field( '-0.25rem' ),
					'field_size'                        => Validatable_Fields\Configuration::integer_field( 16, 0, 50 ),
					'icon'                              => Validatable_Fields\Configuration::string_of_choice_field( 'default', [ 'default', 'fontawesome-check', 'heroicons-check' ] ),
					'icon_color'                        => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'icon_color_on_focus'               => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'icon_color_on_hover'               => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'icon_margin_bottom'                => Validatable_Fields\Configuration::unit_field( '0px' ),
					'icon_margin_left'                  => Validatable_Fields\Configuration::unit_field( '-4px' ),
					'icon_margin_right'                 => Validatable_Fields\Configuration::unit_field( '0px' ),
					'icon_margin_top'                   => Validatable_Fields\Configuration::unit_field( '-3px' ),
					'icon_size'                         => Validatable_Fields\Configuration::integer_field( 21, 0, 50 ),
					'shadow'                            => Validatable_Fields\Configuration::string_field( 'inset 0 1px 2px rgba(0,0,0,.1)' ),
					'shadow_on_focus'                   => Validatable_Fields\Configuration::string_field( '0 0 0 1px #2271b1' ),
					'shadow_on_hover'                   => Validatable_Fields\Configuration::string_field( 'inset 0 1px 2px rgba(0,0,0,.1)' ),
				],
			],
			'login_form_remember_me_checkbox' => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'margin_bottom' => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_left'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'visibility'    => Validatable_Fields\Configuration::string_of_choice_field( 'visible', [ 'visible', 'hidden-checked', 'hidden-unchecked' ] ),
				],
			],
			'login_form_button_primary'       => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'                    => Validatable_Fields\Configuration::string_of_choice_field( 'default', [ 'default', 'new-line-left', 'new-line-center', 'new-line-right' ] ),
					'background_color'             => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'background_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'background_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_bottom_color'          => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_bottom_color_on_focus' => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_bottom_color_on_hover' => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_bottom_left_radius'    => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_bottom_right_radius'   => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_bottom_style'          => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_focus' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_hover' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_width'          => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_focus' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_hover' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_color'            => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_left_color_on_focus'   => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_left_color_on_hover'   => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_left_style'            => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_focus'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_hover'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_width'            => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_focus'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_hover'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_color'           => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_right_color_on_focus'  => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_right_color_on_hover'  => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_right_style'           => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_focus'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_hover'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_width'           => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_focus'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_hover'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_color'             => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'border_top_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_top_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'border_top_left_radius'       => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_top_right_radius'      => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_top_style'             => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_focus'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_hover'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_width'             => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_focus'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_hover'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'font_family'                  => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'                    => Validatable_Fields\Configuration::unit_field( '13px' ),
					'font_weight'                  => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'letter_case'                  => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['letter_case'] ),
					'line_height'                  => Validatable_Fields\Configuration::float_field( 2.31, 0 ),
					'margin_bottom'                => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_left'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'                 => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'                   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_bottom'               => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'                 => Validatable_Fields\Configuration::unit_field( '12px' ),
					'padding_right'                => Validatable_Fields\Configuration::unit_field( '12px' ),
					'padding_top'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'shadow'                       => Validatable_Fields\Configuration::string_field(),
					'shadow_on_focus'              => Validatable_Fields\Configuration::string_field(),
					'shadow_on_hover'              => Validatable_Fields\Configuration::string_field(),
					'text_color'                   => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'text_color_on_focus'          => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'text_color_on_hover'          => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'width'                        => Validatable_Fields\Configuration::string_of_choice_field( 'fit-content', [ 'fit-content', '100%' ] ),
				],
			],
			'login_form_button_secondary'     => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'background_color'             => Validatable_Fields\Configuration::string_field( '#f6f7f7' ),
					'background_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#f6f7f7' ),
					'background_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#f0f0f1' ),
					'border_bottom_color'          => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_bottom_color_on_focus' => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_bottom_color_on_hover' => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'border_bottom_left_radius'    => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_bottom_right_radius'   => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_bottom_style'          => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_focus' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_style_on_hover' => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_bottom_width'          => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_focus' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_bottom_width_on_hover' => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_color'            => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_left_color_on_focus'   => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_left_color_on_hover'   => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'border_left_style'            => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_focus'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_style_on_hover'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_left_width'            => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_focus'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_left_width_on_hover'   => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_color'           => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_right_color_on_focus'  => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_right_color_on_hover'  => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'border_right_style'           => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_focus'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_style_on_hover'  => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_right_width'           => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_focus'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_right_width_on_hover'  => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_color'             => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_top_color_on_focus'    => Validatable_Fields\Configuration::string_field( '#3582c4' ),
					'border_top_color_on_hover'    => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'border_top_left_radius'       => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_top_right_radius'      => Validatable_Fields\Configuration::unit_field( '3px' ),
					'border_top_style'             => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_focus'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_style_on_hover'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'border_top_width'             => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_focus'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'border_top_width_on_hover'    => Validatable_Fields\Configuration::unit_field( '1px' ),
					'padding_bottom'               => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'                 => Validatable_Fields\Configuration::unit_field( '10px' ),
					'padding_right'                => Validatable_Fields\Configuration::unit_field( '10px' ),
					'padding_top'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'shadow'                       => Validatable_Fields\Configuration::string_field(),
					'shadow_on_focus'              => Validatable_Fields\Configuration::string_field( '0 0 0 1px #3582c4' ),
					'shadow_on_hover'              => Validatable_Fields\Configuration::string_field(),
					'text_color'                   => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'text_color_on_focus'          => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'text_color_on_hover'          => Validatable_Fields\Configuration::string_field( '#0a4b78' ),
					'font_family'                  => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'                    => Validatable_Fields\Configuration::unit_field( '13px' ),
					'font_weight'                  => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'letter_case'                  => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['letter_case'] ),
					'line_height'                  => Validatable_Fields\Configuration::float_field( 2.15, 0 ),
				],
			],
			'notices'                         => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'border_bottom_left_radius'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_right_radius'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_left_radius'      => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_right_radius'     => Validatable_Fields\Configuration::unit_field( '0px' ),
					'custom_notice_type'          => Validatable_Fields\Configuration::string_of_choice_field( 'notice', [ 'notice', 'error', 'success' ] ),
					'error_background_color'      => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'error_border_bottom_color'   => Validatable_Fields\Configuration::string_field(),
					'error_border_bottom_style'   => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'error_border_bottom_width'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'error_border_left_color'     => Validatable_Fields\Configuration::string_field( '#d63638' ),
					'error_border_left_style'     => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'error_border_left_width'     => Validatable_Fields\Configuration::unit_field( '4px' ),
					'error_border_right_color'    => Validatable_Fields\Configuration::string_field(),
					'error_border_right_style'    => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'error_border_right_width'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'error_border_top_color'      => Validatable_Fields\Configuration::string_field(),
					'error_border_top_style'      => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'error_border_top_width'      => Validatable_Fields\Configuration::unit_field( '0px' ),
					'error_shadow'                => Validatable_Fields\Configuration::string_field( 'rgba(0, 0, 0, 0.1) 0px 1px 1px 0px' ),
					'error_text_color'            => Validatable_Fields\Configuration::string_field( '#3c434a' ),
					'font_family'                 => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'                   => Validatable_Fields\Configuration::unit_field( '13px' ),
					'font_weight'                 => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'line_height'                 => Validatable_Fields\Configuration::float_field( 1.5, 0 ),
					'margin_bottom'               => Validatable_Fields\Configuration::unit_field( '20px' ),
					'margin_left'                 => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'                => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'notice_background_color'     => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'notice_border_bottom_color'  => Validatable_Fields\Configuration::string_field(),
					'notice_border_bottom_style'  => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'notice_border_bottom_width'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'notice_border_left_color'    => Validatable_Fields\Configuration::string_field( '#72aee6' ),
					'notice_border_left_style'    => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'notice_border_left_width'    => Validatable_Fields\Configuration::unit_field( '4px' ),
					'notice_border_right_color'   => Validatable_Fields\Configuration::string_field(),
					'notice_border_right_style'   => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'notice_border_right_width'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'notice_border_top_color'     => Validatable_Fields\Configuration::string_field(),
					'notice_border_top_style'     => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'notice_border_top_width'     => Validatable_Fields\Configuration::unit_field( '0px' ),
					'notice_shadow'               => Validatable_Fields\Configuration::string_field( 'rgba(0, 0, 0, 0.1) 0px 1px 1px 0px' ),
					'notice_text_color'           => Validatable_Fields\Configuration::string_field( '#3c434a' ),
					'padding_bottom'              => Validatable_Fields\Configuration::unit_field( '12px' ),
					'padding_left'                => Validatable_Fields\Configuration::unit_field( '12px' ),
					'padding_right'               => Validatable_Fields\Configuration::unit_field( '12px' ),
					'padding_top'                 => Validatable_Fields\Configuration::unit_field( '12px' ),
					'show_custom_notice'          => Validatable_Fields\Configuration::boolean_field( false ),
					'success_background_color'    => Validatable_Fields\Configuration::string_field( '#ffffff' ),
					'success_border_bottom_color' => Validatable_Fields\Configuration::string_field(),
					'success_border_bottom_style' => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'success_border_bottom_width' => Validatable_Fields\Configuration::unit_field( '0px' ),
					'success_border_left_color'   => Validatable_Fields\Configuration::string_field( '#00a32a' ),
					'success_border_left_style'   => Validatable_Fields\Configuration::string_of_choice_field( 'solid', $this->common_defs['border_style'] ),
					'success_border_left_width'   => Validatable_Fields\Configuration::unit_field( '4px' ),
					'success_border_right_color'  => Validatable_Fields\Configuration::string_field(),
					'success_border_right_style'  => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'success_border_right_width'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'success_border_top_color'    => Validatable_Fields\Configuration::string_field(),
					'success_border_top_style'    => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'success_border_top_width'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'success_shadow'              => Validatable_Fields\Configuration::string_field( 'rgba(0, 0, 0, 0.1) 0px 1px 1px 0px' ),
					'success_text_color'          => Validatable_Fields\Configuration::string_field( '#3c434a' ),
				],
			],
			'under_form_links'                => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'           => Validatable_Fields\Configuration::string_of_choice_field( 'left', [ 'left', 'center', 'right' ] ),
					'disable_back_link'   => Validatable_Fields\Configuration::boolean_field( false ),
					'font_family'         => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'           => Validatable_Fields\Configuration::unit_field( '13px' ),
					'font_weight'         => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'letter_case'         => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['letter_case'] ),
					'line_height'         => Validatable_Fields\Configuration::float_field( 1.5, 0 ),
					'link_color'          => Validatable_Fields\Configuration::string_field( '#50575e' ),
					'link_color_on_focus' => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'link_color_on_hover' => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'margin_bottom'       => Validatable_Fields\Configuration::unit_field( '16px' ),
					'margin_left'         => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'        => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'          => Validatable_Fields\Configuration::unit_field( '16px' ),
					'padding_bottom'      => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'        => Validatable_Fields\Configuration::unit_field( '24px' ),
					'padding_right'       => Validatable_Fields\Configuration::unit_field( '24px' ),
					'padding_top'         => Validatable_Fields\Configuration::unit_field( '0px' ),
					'separator'           => Validatable_Fields\Configuration::string_field( '|' ),
					'separator_color'     => Validatable_Fields\Configuration::string_field( '#50575e' ),
					'shadow'              => Validatable_Fields\Configuration::string_field(),
					'shadow_on_focus'     => Validatable_Fields\Configuration::string_field( '0 0 0 2px #2271b1' ),
					'shadow_on_hover'     => Validatable_Fields\Configuration::string_field(),
					'text_decoration'     => Validatable_Fields\Configuration::string_of_choice_field( 'none', [ 'none', 'underline', 'line-through' ] ),
				],
			],
			'under_form_links_list'           => [
				'type'   => Validatable_Fields\Dynamic_Fields_Group::TYPE,
				'config' => [
					'under_form_link' => [
						'fields' => [
							'link'            => Validatable_Fields\Configuration::url_field(),
							'open_in_new_tab' => Validatable_Fields\Configuration::boolean_field( false ),
							'text'            => Validatable_Fields\Configuration::string_field(),
							'type'            => Validatable_Fields\Configuration::exact_string_field( 'under_form_link' ),
						],
					],
				],
			],
			'social_media_links'              => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'                    => Validatable_Fields\Configuration::string_of_choice_field( 'center', [ 'left', 'center', 'right' ] ),
					'background_color'             => Validatable_Fields\Configuration::string_field(),
					'background_color_on_focus'    => Validatable_Fields\Configuration::string_field(),
					'background_color_on_hover'    => Validatable_Fields\Configuration::string_field(),
					'border_bottom_color'          => Validatable_Fields\Configuration::string_field(),
					'border_bottom_color_on_focus' => Validatable_Fields\Configuration::string_field(),
					'border_bottom_color_on_hover' => Validatable_Fields\Configuration::string_field(),
					'border_bottom_left_radius'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_right_radius'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_style'          => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_bottom_style_on_focus' => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_bottom_style_on_hover' => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_bottom_width'          => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_width_on_focus' => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_bottom_width_on_hover' => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_left_color'            => Validatable_Fields\Configuration::string_field(),
					'border_left_color_on_focus'   => Validatable_Fields\Configuration::string_field(),
					'border_left_color_on_hover'   => Validatable_Fields\Configuration::string_field(),
					'border_left_style'            => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_left_style_on_focus'   => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_left_style_on_hover'   => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_left_width'            => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_left_width_on_focus'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_left_width_on_hover'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_right_color'           => Validatable_Fields\Configuration::string_field(),
					'border_right_color_on_focus'  => Validatable_Fields\Configuration::string_field(),
					'border_right_color_on_hover'  => Validatable_Fields\Configuration::string_field(),
					'border_right_style'           => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_right_style_on_focus'  => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_right_style_on_hover'  => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_right_width'           => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_right_width_on_focus'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_right_width_on_hover'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_color'             => Validatable_Fields\Configuration::string_field(),
					'border_top_color_on_focus'    => Validatable_Fields\Configuration::string_field(),
					'border_top_color_on_hover'    => Validatable_Fields\Configuration::string_field(),
					'border_top_left_radius'       => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_right_radius'      => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_style'             => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_top_style_on_focus'    => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_top_style_on_hover'    => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['border_style'] ),
					'border_top_width'             => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_width_on_focus'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'border_top_width_on_hover'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'gap'                          => Validatable_Fields\Configuration::unit_field( '1em' ),
					'icon_color'                   => Validatable_Fields\Configuration::string_field( '#3c434a' ),
					'icon_color_on_focus'          => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'icon_color_on_hover'          => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'icon_size'                    => Validatable_Fields\Configuration::unit_field( '20px' ),
					'margin_bottom'                => Validatable_Fields\Configuration::unit_field( '16px' ),
					'margin_left'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'                 => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'                   => Validatable_Fields\Configuration::unit_field( '16px' ),
					'padding_bottom'               => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'                 => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_right'                => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_top'                  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'placement'                    => Validatable_Fields\Configuration::string_of_choice_field( 'at_the_bottom', [ 'above_logo', 'above_form', 'above_inline_links', 'above_privacy_policy_link', 'above_language_switcher', 'at_the_bottom' ] ),
					'shadow'                       => Validatable_Fields\Configuration::string_field(),
					'shadow_on_focus'              => Validatable_Fields\Configuration::string_field( '0 0 0 2px #2271b1' ),
					'shadow_on_hover'              => Validatable_Fields\Configuration::string_field(),
					'show'                         => Validatable_Fields\Configuration::boolean_field( false ),
				],
			],
			'social_media_links_list'         => [
				'type'   => Validatable_Fields\Dynamic_Fields_Group::TYPE,
				'config' => [
					'social_media_link' => [
						'fields' => [
							'aria_label'      => Validatable_Fields\Configuration::string_field(),
							'icon'            => Validatable_Fields\Configuration::string_of_choice_field( 'fontawesome-facebook-f', $this->common_defs['social_media_icons'] ),
							'link'            => Validatable_Fields\Configuration::url_field( '' ),
							'open_in_new_tab' => Validatable_Fields\Configuration::boolean_field( false ),
							'type'            => Validatable_Fields\Configuration::exact_string_field( 'social_media_link' ),
						],
					],
				],
			],
			'privacy_policy_link'             => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'           => Validatable_Fields\Configuration::string_of_choice_field( 'center', [ 'left', 'center', 'right' ] ),
					'font_family'         => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'           => Validatable_Fields\Configuration::unit_field( '13px' ),
					'font_weight'         => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'hide'                => Validatable_Fields\Configuration::boolean_field( false ),
					'letter_case'         => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['letter_case'] ),
					'line_height'         => Validatable_Fields\Configuration::float_field( 1.4, 0 ),
					'link_color'          => Validatable_Fields\Configuration::string_field( '#2271b1' ),
					'link_color_on_focus' => Validatable_Fields\Configuration::string_field( '#135e96' ),
					'link_color_on_hover' => Validatable_Fields\Configuration::string_field( '#043959' ),
					'margin_bottom'       => Validatable_Fields\Configuration::unit_field( '2em' ),
					'margin_left'         => Validatable_Fields\Configuration::unit_field( '0em' ),
					'margin_right'        => Validatable_Fields\Configuration::unit_field( '0em' ),
					'margin_top'          => Validatable_Fields\Configuration::unit_field( '3em' ),
					'padding_bottom'      => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'        => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_right'       => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_top'         => Validatable_Fields\Configuration::unit_field( '0px' ),
					'shadow'              => Validatable_Fields\Configuration::string_field(),
					'shadow_on_focus'     => Validatable_Fields\Configuration::string_field( '0 0 0 2px #2271b1' ),
					'shadow_on_hover'     => Validatable_Fields\Configuration::string_field(),
					'text_decoration'     => Validatable_Fields\Configuration::string_of_choice_field( 'underline', [ 'none', 'underline', 'line-through' ] ),
				],
			],
			'language_switcher'               => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'icon_color'     => Validatable_Fields\Configuration::string_field( '#3c434a' ),
					'show'           => Validatable_Fields\Configuration::boolean_field( true ),
					'margin_bottom'  => Validatable_Fields\Configuration::unit_field( '24px' ),
					'margin_left'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_right'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'margin_top'     => Validatable_Fields\Configuration::unit_field( '24px' ),
					'padding_bottom' => Validatable_Fields\Configuration::unit_field( '24px' ),
					'padding_left'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_right'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_top'    => Validatable_Fields\Configuration::unit_field( '0px' ),
				],
			],
			'footer'                          => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'alignment'       => Validatable_Fields\Configuration::string_of_choice_field( 'center', [ 'left', 'center', 'right' ] ),
					'font_family'     => Validatable_Fields\Configuration::string_of_choice_field( 'default', $this->common_defs['font_families'] ),
					'font_size'       => Validatable_Fields\Configuration::unit_field( '13px' ),
					'font_weight'     => Validatable_Fields\Configuration::string_of_choice_field( '400', $this->common_defs['font_weights'] ),
					'letter_case'     => Validatable_Fields\Configuration::string_of_choice_field( 'none', $this->common_defs['letter_case'] ),
					'line_height'     => Validatable_Fields\Configuration::float_field( 1.4, 0 ),
					'margin_bottom'   => Validatable_Fields\Configuration::unit_field( '1em' ),
					'margin_left'     => Validatable_Fields\Configuration::unit_field( '0em' ),
					'margin_right'    => Validatable_Fields\Configuration::unit_field( '0em' ),
					'margin_top'      => Validatable_Fields\Configuration::unit_field( '1em' ),
					'padding_bottom'  => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_left'    => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_right'   => Validatable_Fields\Configuration::unit_field( '0px' ),
					'padding_top'     => Validatable_Fields\Configuration::unit_field( '0px' ),
					'text_color'      => Validatable_Fields\Configuration::string_field( '#50575e' ),
					'text_decoration' => Validatable_Fields\Configuration::string_of_choice_field( 'none', [ 'none', 'underline', 'line-through' ] ),
					'text'            => Validatable_Fields\Configuration::string_field( '' ),
				],
			],
			'miscellaneous'                   => [
				'type'   => Validatable_Fields\Fields_Group::TYPE,
				'config' => [
					'disable_autocomplete' => Validatable_Fields\Configuration::boolean_field( false ),
					'disable_autofocus'    => Validatable_Fields\Configuration::boolean_field( false ),
					'disable_shake_effect' => Validatable_Fields\Configuration::boolean_field( false ),
				],
			],
		];

		/**
		 * Add language-specific fields
		 */
		foreach ( $languages as $lang ) {
			// For "logo" group.
			$fields_config['logo']['config'][ sprintf( 'link_title.%s', $lang ) ] = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Powered by WordPress', $lang ) );

			// For "login form labels" group.
			$fields_config['login_form_labels']['config'][ sprintf( 'label_email.%s', $lang ) ]                     = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Email', $lang ) );
			$fields_config['login_form_labels']['config'][ sprintf( 'label_password.%s', $lang ) ]                  = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Password', $lang ) );
			$fields_config['login_form_labels']['config'][ sprintf( 'label_username.%s', $lang ) ]                  = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Username', $lang ) );
			$fields_config['login_form_labels']['config'][ sprintf( 'label_username_or_email_address.%s', $lang ) ] = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Username or Email Address', $lang ) );

			// For "login form input fields" group.
			$fields_config['login_form_input_fields']['config'][ sprintf( 'placeholder_email.%s', $lang ) ]                     = Validatable_Fields\Configuration::string_field();
			$fields_config['login_form_input_fields']['config'][ sprintf( 'placeholder_password.%s', $lang ) ]                  = Validatable_Fields\Configuration::string_field();
			$fields_config['login_form_input_fields']['config'][ sprintf( 'placeholder_username.%s', $lang ) ]                  = Validatable_Fields\Configuration::string_field();
			$fields_config['login_form_input_fields']['config'][ sprintf( 'placeholder_username_or_email_address.%s', $lang ) ] = Validatable_Fields\Configuration::string_field();

			// For "login form remember me checkbox" group.
			$fields_config['login_form_remember_me_checkbox']['config'][ sprintf( 'label_remember_me.%s', $lang ) ] = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Remember Me', $lang ) );

			// For "login form button primary" group.
			$fields_config['login_form_button_primary']['config'][ sprintf( 'label_get_new_password.%s', $lang ) ] = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Get New Password', $lang ) );
			$fields_config['login_form_button_primary']['config'][ sprintf( 'label_log_in.%s', $lang ) ]           = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Log In', $lang ) );
			$fields_config['login_form_button_primary']['config'][ sprintf( 'label_register.%s', $lang ) ]         = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Register', $lang ) );
			$fields_config['login_form_button_primary']['config'][ sprintf( 'label_save_password.%s', $lang ) ]    = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Save Password', $lang ) );

			// For "login form button secondary" group.
			$fields_config['login_form_button_secondary']['config'][ sprintf( 'label_change.%s', $lang ) ]            = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Change', $lang ) );
			$fields_config['login_form_button_secondary']['config'][ sprintf( 'label_generate_password.%s', $lang ) ] = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Generate Password', $lang ) );

			// For "notices" group.
			$fields_config['notices']['config'][ sprintf( 'notice_custom.%s', $lang ) ]         = Validatable_Fields\Configuration::string_field();
			$fields_config['notices']['config'][ sprintf( 'notice_password_reset.%s', $lang ) ] = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Please enter your username or email address. You will receive an email message with instructions on how to reset your password.', $lang ) );
			$fields_config['notices']['config'][ sprintf( 'notice_register.%s', $lang ) ]       = Validatable_Fields\Configuration::string_field( Utils\Languages::get_single_translation( 'Register For This Site', $lang ) );
		}

		/**
		 * Allow other plugins and modules to filter
		 * the settings fields configuration
		 *
		 * @param Type_Settings_Fields_Config $fields_config Configuration of the settings fields.
		 */
		return apply_filters( 'custom_login__settings_fields_config', $fields_config );
	}
}
