<?php
/**
 * Get the plugin classmap
 *
 * @package Teydea_Studio\Custom_Login
 */

return [
	'Teydea_Studio\\Custom_Login\\Adjuster' => '/src/class-adjuster.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Universal_Modules\\Module_Endpoint_Settings' => '/deps/php/universal-modules/class-module-endpoint-settings.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Universal_Modules\\Module_Plugin_Upgrade_Action_Link' => '/deps/php/universal-modules/class-module-plugin-upgrade-action-link.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Universal_Modules\\Module_Settings_Page' => '/deps/php/universal-modules/class-module-settings-page.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Universal_Modules\\Module_Translations' => '/deps/php/universal-modules/class-module-translations.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Asset' => '/deps/php/utils/class-asset.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Cache' => '/deps/php/utils/class-cache.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Container' => '/deps/php/utils/class-container.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Date_Time' => '/deps/php/utils/class-date-time.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Environment' => '/deps/php/utils/class-environment.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Languages' => '/deps/php/utils/class-languages.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Module' => '/deps/php/utils/class-module.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Nonce' => '/deps/php/utils/class-nonce.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Plugin' => '/deps/php/utils/class-plugin.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Screen' => '/deps/php/utils/class-screen.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Settings' => '/deps/php/utils/class-settings.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Strings' => '/deps/php/utils/class-strings.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Type' => '/deps/php/utils/class-type.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\User' => '/deps/php/utils/class-user.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Utils\\Users' => '/deps/php/utils/class-users.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Closures' => '/deps/php/validatable-fields/class-closures.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Configuration' => '/deps/php/validatable-fields/class-configuration.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Dynamic_Fields_Group' => '/deps/php/validatable-fields/class-dynamic-fields-group.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field' => '/deps/php/validatable-fields/class-field.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field_Array_Of_Strings' => '/deps/php/validatable-fields/class-field-array-of-strings.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field_Boolean' => '/deps/php/validatable-fields/class-field-boolean.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field_Float' => '/deps/php/validatable-fields/class-field-float.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field_Integer' => '/deps/php/validatable-fields/class-field-integer.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field_String' => '/deps/php/validatable-fields/class-field-string.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Field_String_Of_Choice' => '/deps/php/validatable-fields/class-field-string-of-choice.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Fields_Group' => '/deps/php/validatable-fields/class-fields-group.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Key_Identifiable' => '/deps/php/validatable-fields/trait-key-identifiable.php',
	'Teydea_Studio\\Custom_Login\\Dependencies\\Validatable_Fields\\Validatable' => '/deps/php/validatable-fields/trait-validatable.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Background' => '/src/modules/adjustments/adjusters/class-adjuster-background.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Footer' => '/src/modules/adjustments/adjusters/class-adjuster-footer.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Language_Switcher' => '/src/modules/adjustments/adjusters/class-adjuster-language-switcher.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Button_Primary' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-button-primary.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Button_Secondary' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-button-secondary.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Checkbox_Fields' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-checkbox-fields.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Container' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-container.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Input_Fields' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-input-fields.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Labels' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-labels.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Login_Form_Remember_Me_Checkbox' => '/src/modules/adjustments/adjusters/class-adjuster-login-form-remember-me-checkbox.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Logo' => '/src/modules/adjustments/adjusters/class-adjuster-logo.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Notices' => '/src/modules/adjustments/adjusters/class-adjuster-notices.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Privacy_Policy_Link' => '/src/modules/adjustments/adjusters/class-adjuster-privacy-policy-link.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Social_Media_Links' => '/src/modules/adjustments/adjusters/class-adjuster-social-media-links.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Adjustments\\Adjuster_Under_Form_Links' => '/src/modules/adjustments/adjusters/class-adjuster-under-form-links.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Adjustments' => '/src/modules/adjustments/class-module-adjustments.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Endpoint_Preview' => '/src/modules/class-module-endpoint-preview.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Markup_Adjustments' => '/src/modules/class-module-markup-adjustments.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Miscellaneous' => '/src/modules/class-module-miscellaneous.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Plugin_Upgrade_Action_Link' => '/src/modules/class-module-plugin-upgrade-action-link.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Settings_Adopter' => '/src/modules/class-module-settings-adopter.php',
	'Teydea_Studio\\Custom_Login\\Modules\\Module_Settings_Page' => '/src/modules/settings-page/class-module-settings-page.php',
	'Teydea_Studio\\Custom_Login\\Settings' => '/src/class-settings.php',
	'Teydea_Studio\\Custom_Login\\Styles' => '/src/class-styles.php',
];
